### ISSUE TITLE
Move redirections to subdomains

### ISSUE THREAD

**Issue by narayanaditya95** [Robotix/Robotix.github.io#1]
The main website <www.robotix.in> should not be used for any redirection. All redirections must reside within their own subdomains, like <app.robotix.in>.

Remove the following redirections:
- www.robotix.in/app
- www.robotix.in/recruit

**Comment by shivangag** [comment]
I removed the redirections.
Let this issue be open for future reference?

**Comment by narayanaditya95** [comment]
Why doesn't <http://recruit.robotix.in> work?

**Comment by shivangag** [comment]
It doesn't have to work right now. The google form will change every year, so the new link will be added when required.

**Comment by narayanaditya95** [comment]
Add last year's form link. Update when required.
