### ISSUE TITLE
Investigate MathJax requests

### ISSUE THREAD

**Issue by narayanaditya95** [Robotix/Robotix.github.io#8]
Why are we requesting MathJax's assets during page load? See [request log](https://tools.pingdom.com/#!/b2Dbn/https://www.robotix.in/).

**Comment by narayanaditya95** [comment]
@shivangag Can you look into it?

**Comment by shivangag** [comment]
It was added in [this](https://github.com/Robotix/Robotix.github.io/commit/c18d646eda136fbfb1a412e32b76e9a27175ac4d) commit to render the equations in [this](https://www.robotix.in/tutorial/advanced/kalman_filter/) blog post.
